package com.zhoujk.pojo;

import java.io.Serializable;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user2.id
     *
     * @mbg.generated Mon Sep 27 14:39:59 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user2.age
     *
     * @mbg.generated Mon Sep 27 14:39:59 CST 2021
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user2
     *
     * @mbg.generated Mon Sep 27 14:39:59 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2
     *
     * @mbg.generated Mon Sep 27 14:39:59 CST 2021
     */
    public User(Integer id, Integer age) {
        this.id = id;
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2
     *
     * @mbg.generated Mon Sep 27 14:39:59 CST 2021
     */
    public User() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user2.id
     *
     * @return the value of user2.id
     *
     * @mbg.generated Mon Sep 27 14:39:59 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user2.id
     *
     * @param id the value for user2.id
     *
     * @mbg.generated Mon Sep 27 14:39:59 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user2.age
     *
     * @return the value of user2.age
     *
     * @mbg.generated Mon Sep 27 14:39:59 CST 2021
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user2.age
     *
     * @param age the value for user2.age
     *
     * @mbg.generated Mon Sep 27 14:39:59 CST 2021
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}