package com.zhoujk.pojo;

import java.io.Serializable;

public class UserWithBLOBs extends User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user2.username
     *
     * @mbg.generated Mon Sep 27 14:39:59 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user2.password
     *
     * @mbg.generated Mon Sep 27 14:39:59 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user2.sex
     *
     * @mbg.generated Mon Sep 27 14:39:59 CST 2021
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user2.hobby
     *
     * @mbg.generated Mon Sep 27 14:39:59 CST 2021
     */
    private String hobby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user2.remark
     *
     * @mbg.generated Mon Sep 27 14:39:59 CST 2021
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user2
     *
     * @mbg.generated Mon Sep 27 14:39:59 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2
     *
     * @mbg.generated Mon Sep 27 14:39:59 CST 2021
     */
    public UserWithBLOBs(Integer id, Integer age, String username, String password, String sex, String hobby, String remark) {
        super(id, age);
        this.username = username;
        this.password = password;
        this.sex = sex;
        this.hobby = hobby;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2
     *
     * @mbg.generated Mon Sep 27 14:39:59 CST 2021
     */
    public UserWithBLOBs() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user2.username
     *
     * @return the value of user2.username
     *
     * @mbg.generated Mon Sep 27 14:39:59 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user2.username
     *
     * @param username the value for user2.username
     *
     * @mbg.generated Mon Sep 27 14:39:59 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user2.password
     *
     * @return the value of user2.password
     *
     * @mbg.generated Mon Sep 27 14:39:59 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user2.password
     *
     * @param password the value for user2.password
     *
     * @mbg.generated Mon Sep 27 14:39:59 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user2.sex
     *
     * @return the value of user2.sex
     *
     * @mbg.generated Mon Sep 27 14:39:59 CST 2021
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user2.sex
     *
     * @param sex the value for user2.sex
     *
     * @mbg.generated Mon Sep 27 14:39:59 CST 2021
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user2.hobby
     *
     * @return the value of user2.hobby
     *
     * @mbg.generated Mon Sep 27 14:39:59 CST 2021
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user2.hobby
     *
     * @param hobby the value for user2.hobby
     *
     * @mbg.generated Mon Sep 27 14:39:59 CST 2021
     */
    public void setHobby(String hobby) {
        this.hobby = hobby == null ? null : hobby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user2.remark
     *
     * @return the value of user2.remark
     *
     * @mbg.generated Mon Sep 27 14:39:59 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user2.remark
     *
     * @param remark the value for user2.remark
     *
     * @mbg.generated Mon Sep 27 14:39:59 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}